name:                uncertain
version:             0.3.1.0
github:              mstksg/uncertain
license:             BSD3
author:              Justin Le
maintainer:          justin@jle.im
copyright:           (c) Justin Le 2018
tested-with:         GHC >= 8.0

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Manipulating numbers with inherent experimental/measurement uncertainty
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
    See <https://github.com/mstksg/uncertain/blob/master/README.md README.md>.

    Documentation maintained at <https://mstksg.github.io/uncertain>

ghc-options:
- -Wall

dependencies:
- base >=4.6 && <5
- ad >=4
- containers >=0.5
- free >=4
- mwc-random >=0.10
- primitive >=0.1
- transformers >=0.2
- base-compat

library:
  source-dirs: src
  exposed-modules:
  - Numeric.Uncertain
  - Numeric.Uncertain.Correlated
  - Numeric.Uncertain.Correlated.Interactive
  - Numeric.Uncertain.MonteCarlo
  other-modules:
  - Data.Hople
  - Numeric.Uncertain.Correlated.Internal
